apiVersion: v1
kind: Service
metadata:
  name: {{.Web.BinaryName}}
  labels:
    app: {{.Web.BinaryName}}
spec:
  type: NodePort
  selector:
    app: {{.Web.BinaryName}}
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5555
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
