apiVersion: v1
kind: ConfigMap
metadata:
  name: mb-apiserver
  labels:
    app: mb-apiserver
data:
  mb-apiserver.yaml: |-
    otel:
      endpoint: 127.0.0.1:4317
      service-name: mb-apiserver
      output-mode: legacy
      level: debug
      add-source: true
      use-prometheus-endpoint: true
      slog: # Only effective when --otel.user-native-slog is true
        format: json           # Only effective when output-mode is slog
        time-format: "2006-01-02 15:04:05"  # Only effective when output-mode is slog
        output: stdout         # Only effective when output-mode is slog
    fake:
      endpoint: http://127.0.0.1:9999
      user-agent: mb-apiserver
      debug: true
      timeout: 30s
      retry-count: 3
